update

diff --git a/.local/bin/run b/.local/bin/run
--- a/.local/bin/run
+++ b/.local/bin/run
@@ -6,19 +6,12 @@ path=$(pwd)
 project=$(basename $path)
 
 case "$project" in
-  'explorer')
-    RUN_COMMAND="bundle exec rails s -p 3000" ;;
-  'graphql') 
-    RUN_COMMAND="bundle exec rails s -p 3001" ;;
-  'bloxyapi') 
-    RUN_COMMAND="bundle exec rails s -p 3002" ;;
-  'spy') 
-    RUN_COMMAND="PORT=3003 bundle exec pumactl -F config/puma.api.rb start" ;;
-  'wittyjudge.github.io') 
-    RUN_COMMAND="hugo server -D -p 1313" ;;
-  *) 
-    echo "Runner for '$project' project not found"
-    exit 1
+'wittyjudge.github.io')
+  RUN_COMMAND="hugo server -D -p 1313"
+  ;;
+*)
+  echo "Runner for '$project' project not found"
+  exit 1
   ;;
 esac
 
